name: Repository Dispatch
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: RO-Crate to Pages
        uses: vliz-be-opsci/profile-repository-to-pages@latest
        with:
          base_uri: https://oliverwoolland.github.io/ro-crate-profile-repository/
      - name: Debug - List all files after RO-Crate
        run: ls -R .
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./unicornpages
